FROM php:7.2-apache
COPY conf /etc/apache2

RUN apt-get update && \
	apt-get install -y nano

COPY apache2-foreground /usr/local/bin/
COPY templates /var/apache2/templates

RUN a2enmod proxy proxy_http proxy_balancer lbmethod_byrequests headers
RUN a2ensite 000-* 001-*


